### ISSUE TITLE
NullReferenceException when generating proxy for systemd unit

### ISSUE THREAD

**Issue by SS1823** [affederaffe/Tmds.DBus.SourceGenerator#30]
Generate the xml
```
busctl introspect org.freedesktop.systemd1 /org/freedesktop/systemd1/job --xml-interface  > systemd-unit.xml
```

The generator output:
```
   1:7>CSC : warning CS8785: Generator 'DBusSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'. [(omitted)/dbus.csproj]
         System.NullReferenceException: Object reference not set to an instance of an object.
         at Tmds.DBus.SourceGenerator.DBusSourceGenerator.SanitizeSignature(String signature)
         at Tmds.DBus.SourceGenerator.DBusSourceGenerator.GetOrAddWriteVariantMethod(DBusValue dBusValue)
         at Tmds.DBus.SourceGenerator.DBusSourceGenerator.MakeSetMethod(DBusProperty dBusProperty)
         at Tmds.DBus.SourceGenerator.DBusSourceGenerator.<AddProperties>b__46_0(ClassDeclarationSyntax current, DBusProperty dBusProperty)
         at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
         at Tmds.DBus.SourceGenerator.DBusSourceGenerator.AddProperties(ClassDeclarationSyntax& cl, DBusInterface dBusInterface)
         at Tmds.DBus.SourceGenerator.DBusSourceGenerator.GenerateProxy(DBusInterface dBusInterface)
         at Tmds.DBus.SourceGenerator.DBusSourceGenerator.<>c__DisplayClass8_0.<Initialize>b__4(SourceProductionContext productionContext, ImmutableArray`1 provider)
         at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass3_0`2.<WrapUserAction>b__0(TInput1 input1, TInput2 input2, CancellationToken token)
         -----
```

**Comment by SS1823** [comment]
Rolling back the generator to 0.0.18 fixes the problem

**Comment by affederaffe** [comment]
Not reproducible with the latest version (0.0.20).
Could you update to the new release and report back if this fixes your issue?

**Comment by ash-microconnect** [comment]
@SS1823 This looks similar/same as https://github.com/affederaffe/Tmds.DBus.SourceGenerator/issues/26, in which case this has been fixed in the latest version.
